# Generated by Django 3.0.3 on 2022-05-13 05:01

import django.core.validators
from django.db import migrations, models
import romannumeralconverter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('arabic_number', models.IntegerField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), romannumeralconverter.models.Numeral.validate_max_value])),
            ],
        ),
    ]
