# Generated by Django 3.0.3 on 2022-05-13 07:59

from django.db import migrations, models
import romannumeralconverter.models


class Migration(migrations.Migration):

    dependencies = [
        ('romannumeralconverter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeral',
            name='roman_number',
            field=models.CharField(default='ROMAN_CHAR?', max_length=10, validators=[romannumeralconverter.models.Numeral.validate_roman_characters]),
        ),
    ]
